[package]
name = "snippet"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[dependencies]
anyhow = "1.0.86"
tempfile = "3.12.0"
walkdir = "2.5.0"
zip = "2.2.0"

[target.'cfg(windows)'.dependencies]
winsplit = "0.1.0"

[target.'cfg(not(windows))'.dependencies]
shlex = "1.3.0"
